# Generated by Django 3.1.5 on 2021-03-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('website', '0003_auto_20210216_0151'),
	]

	operations = [
		migrations.RenameModel('Subscription', 'Author'),
	]