# Generated by Django 3.1.5 on 2021-03-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('website', '0004_auto_20210317_2103'),
	]

	operations = [
	]
