# Generated by Django 4.0.2 on 2022-03-23 19:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_story_is_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_fuzzy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='fuzzy_ratio',
            field=models.IntegerField(default=80),
        ),
    ]
